### ISSUE TITLE
Add support for PromiseRejectionEvents being fired on workers

### ISSUE THREAD

**Issue by domenic** [domenic/unhandled-rejections-browser-spec#1]
HTML does it for script errors. We should do it for promise rejections as well.

**Comment by jeisinger** [comment]
I don't think that's desirable. workers can be in a different process, and we can't transfer promises and arbitrary reasons across processes, so the event would basically carry zero information

**Comment by domenic** [comment]
@bzbarsky would like your blessing to abandon this idea. As @jeisinger says, it's not really feasible, since neither promises nor promise rejections (which are often Errors, but could be anything) are structured-cloneable.

We could force it to work, by switching from promises to UA-generated promise IDs, and adding message/lineno/colno/filename which can be non-empty for workers even though reason would be empty. But that seems not worth it, given that the use case is pretty darn unclear here.

**Comment by jeisinger** [comment]
@bzbarsky friendly ping?

**Comment by bzbarsky** [comment]
So the basic question is how reporting unhandled promise rejections in a worker should work.  The use cases are much the same as reporting unhandled promise rejections in a window: finding, catching, and reporting logic errors in your code.  So I'm not sure what's unclear about the use cases.  I feel like there's some major disconnect between my thinking and @domenic's here, which is worrying; I'd like to understand what I'm missing.  ;)

For purposes of said reporting, what's needed is a report when there is an unhandled rejection (which would presumably include information about the rejection) and a report when it gets handled which can be correlated to the earlier report.  None of that seems infeasible in workers, though you're right that the promise object identity can't be used as the correlation method.

> so the event would basically carry zero information

Generally speaking, the event can carry a message, a stack to where the Error the promise was rejected with was created, a stack to where the promise was rejecte, and a stack to where the promise was allocated (insofar as any of those happened while there was script to get a stack of).  It can also carry the URI of the worker for the edge cases when all the promise stuff happened completely async in the browser guts.  Maybe some other useful strings are also possible; I'd have to think about that.  I wouldn't characterize that as 0 information...

**Comment by domenic** [comment]
> So the basic question is how reporting unhandled promise rejections in a worker should work

My basic answer is that you should import the same script you would use in a window, which does e.g. `self.addEventListener("unhandledrejection", ...)`. I don't have a complete picture of how `workerInstance.addEventListener("error", ...)` is used, versus `self.addEventListener("error", ..)` inside the worker. But the latter seems more usable to me than the former in general---e.g. the latter can get the whole `error` object, instead of just the message/filename/lineno/colno.

> Generally speaking, the event can carry a message, a stack to where the Error the promise was rejected with was created, a stack to where the promise was rejecte, and a stack to where the promise was allocated (insofar as any of those happened while there was script to get a stack of)

Right, I guess that is true. I'm hesitant to do it given that there's no precedent for taking stacks and serializing them across frames, especially given that the stack trace format itself is still not standardized :(. We could of course do similar (message, filename, lineno, colno) hacks as ErrorEvent does.

But in general my thinking is that the primary motivation for `workerInstance.addEventListener("unhandledrejection", ...)` is symmetry, not actual utility. Doing `self.addEventListener("unhandledrejection", ...)` inside the worker makes a lot more sense to me on a practical level. So that is why I am not too worried about supporting the former.

**Comment by bzbarsky** [comment]
OK, so the point is that we'd still fire the promise rejection stuff _inside_ the worker, but leave it to the consumer to propagate it out of the worker as they deem fit?  I thought we were talking about not firing things inside the worker at all; that explains what I was missing.  ;)

I'm fine with not auto-propagating things across to the Worker instance for a start.  We can see what people do in practice to propagate things out and then add something if we decide it's needed.

**Comment by domenic** [comment]
Excellent! Yeah, I believe the current spec does the inside-the-worker stuff just fine, unless I accidentally used something window-specific. So, closing this issue!
