### ISSUE TITLE
Censor events for cross-origin scripts

### ISSUE THREAD

**Issue by jeisinger** [domenic/unhandled-rejections-browser-spec#20]
If a script was loaded from a cross-origin URL without CORS access, we should censor the events / or not send them at all.

**Comment by domenic** [comment]
Done in spec-land in https://github.com/whatwg/html/commit/d7e1571d4e3f526f611749116d6c1f1525c78098... now let's see if I can figure out how to write some tests :-S

**Comment by jeisinger** [comment]
is "muted errors" defined somewhere?

**Comment by domenic** [comment]
https://html.spec.whatwg.org/#muted-errors

**Comment by domenic** [comment]
Also relevant is https://html.spec.whatwg.org/#the-script-element:create-a-script which plumbs the flag through

**Comment by jeisinger** [comment]
hum, so there are three "scripts" we could consider: the script that created the promise, the script that rejected it, or the script that created the reason.

which one should we use for the is muted check?

Implementation wise, we currently use "reason" to display the stack in devtools, however, that means that if you e.g. new Promise(function(a,b) { b(1); }); you won't get a stack trace.

**Comment by domenic** [comment]
The spec is that it's the script that rejected it, similar to how it's the script that throws an error that we use for window.onerror's muted check. (There the choices are fewer: the script that threw the error, and the script that created the error.)

I'm not sure I understand the relevance of your last paragraph...
